### ISSUE TITLE
Game crashes after getting off ski inside lava

### ISSUE THREAD

**Issue by Pezcraft** [Affehund/Skiing#5]
I skied down a cave and stopped inside lava. Then I sneaked to get off the skies, and suddenly the game crashed. After rejoining the world, it crashes after 1s.

Crash log:
`
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 1/4/22, 12:48 AM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?] {}
	at com.affehund.skiing.common.entity.AbstractControllableEntity.m_6469_(AbstractControllableEntity.java:106) ~[skiing-forge-1.18.1-1.0.0.jar%2353!:1.18.1-1.0.0] {re:classloading}
	at net.minecraft.world.entity.Entity.m_6075_(Entity.java:447) ~[client-1.18.1-20211210.034407-srg.jar%2354!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.entity.Entity.m_8119_(Entity.java:410) ~[client-1.18.1-20211210.034407-srg.jar%2354!:?] {re:classloading,pl:accesstransformer:B}
	at com.affehund.skiing.common.entity.AbstractControllableEntity.m_8119_(AbstractControllableEntity.java:76) ~[skiing-forge-1.18.1-1.0.0.jar%2353!:1.18.1-1.0.0] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:649) ~[client-1.18.1-20211210.034407-srg.jar%2354!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.Level.m_46653_(Level.java:487) ~[client-1.18.1-20211210.034407-srg.jar%2354!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:316) ~[client-1.18.1-20211210.034407-srg.jar%2354!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.18.1-20211210.034407-srg.jar%2354!:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:296) ~[client-1.18.1-20211210.034407-srg.jar%2354!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:868) ~[client-1.18.1-20211210.034407-srg.jar%2354!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[client-1.18.1-20211210.034407-srg.jar%2354!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:120) ~[client-1.18.1-20211210.034407-srg.jar%2354!:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[client-1.18.1-20211210.034407-srg.jar%2354!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.18.1-20211210.034407-srg.jar%2354!:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?] {}
	at com.affehund.skiing.common.entity.AbstractControllableEntity.m_6469_(AbstractControllableEntity.java:106) ~[skiing-forge-1.18.1-1.0.0.jar%2353!:1.18.1-1.0.0] {re:classloading}
	at net.minecraft.world.entity.Entity.m_6075_(Entity.java:447) ~[client-1.18.1-20211210.034407-srg.jar%2354!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.entity.Entity.m_8119_(Entity.java:410) ~[client-1.18.1-20211210.034407-srg.jar%2354!:?] {re:classloading,pl:accesstransformer:B}
	at com.affehund.skiing.common.entity.AbstractControllableEntity.m_8119_(AbstractControllableEntity.java:76) ~[skiing-forge-1.18.1-1.0.0.jar%2353!:1.18.1-1.0.0] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:649) ~[client-1.18.1-20211210.034407-srg.jar%2354!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.Level.m_46653_(Level.java:487) ~[client-1.18.1-20211210.034407-srg.jar%2354!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:316) ~[client-1.18.1-20211210.034407-srg.jar%2354!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.18.1-20211210.034407-srg.jar%2354!:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:296) ~[client-1.18.1-20211210.034407-srg.jar%2354!:?] {re:classloading,pl:accesstransformer:B}
-- Entity being ticked --
Details:
	Entity Type: skiing:ski (com.affehund.skiing.common.entity.SkiEntity)
	Entity ID: 96
	Entity Name: Ski
	Entity's Exact location: 1759.28, 43.00, 1819.69
	Entity's Block location: World: (1759,43,1819), Section: (at 15,11,11 in 109,2,113; chunk contains blocks 1744,-64,1808 to 1759,319,1823), Region: (3,3; contains chunks 96,96 to 127,127, blocks 1536,-64,1536 to 2047,319,2047)
	Entity's Momentum: -0.00, 0.00, 0.00
	Entity's Passengers: [ServerPlayer['PezcraftYT'/95, l='ServerLevel[Ski Mod]', x=1759.28, y=43.00, z=1819.69]]
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.world.level.Level.m_46653_(Level.java:487) ~[client-1.18.1-20211210.034407-srg.jar%2354!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:316) ~[client-1.18.1-20211210.034407-srg.jar%2354!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.18.1-20211210.034407-srg.jar%2354!:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:296) ~[client-1.18.1-20211210.034407-srg.jar%2354!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:868) ~[client-1.18.1-20211210.034407-srg.jar%2354!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[client-1.18.1-20211210.034407-srg.jar%2354!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:120) ~[client-1.18.1-20211210.034407-srg.jar%2354!:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[client-1.18.1-20211210.034407-srg.jar%2354!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.18.1-20211210.034407-srg.jar%2354!:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

-- Affected level --
Details:
	All players: 1 total; [ServerPlayer['PezcraftYT'/95, l='ServerLevel[Ski Mod]', x=1759.28, y=43.00, z=1819.69]]
	Chunk stats: 21251
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,66,32), Section: (at 0,2,0 in 0,4,2; chunk contains blocks 0,-64,32 to 15,319,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 40836 game time, 17538 day time
	Level name: Ski Mod
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 135532 (now: false), thunder time: 117779 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:868) ~[client-1.18.1-20211210.034407-srg.jar%2354!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[client-1.18.1-20211210.034407-srg.jar%2354!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:120) ~[client-1.18.1-20211210.034407-srg.jar%2354!:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[client-1.18.1-20211210.034407-srg.jar%2354!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.18.1-20211210.034407-srg.jar%2354!:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1397945224 bytes (1333 MiB) / 3351248896 bytes (3196 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): 2.59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: Intel(R) UHD Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x9bc4
	Graphics card #0 versionInfo: DriverVersion=27.20.100.9168
	Graphics card #1 name: NVIDIA GeForce GTX 1650 Ti
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x1f95
	Graphics card #1 versionInfo: DriverVersion=27.21.14.6231
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 26369.69
	Virtual memory used (MB): 20809.23
	Swap memory total (MB): 10240.00
	Swap memory used (MB): 1254.44
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['PezcraftYT'/95, l='ServerLevel[Ski Mod]', x=1759.28, y=43.00, z=1819.69]]
	Data Packs: vanilla, mod:skiing, mod:forge
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	OptiFine Version: OptiFine_1.18.1_HD_U_H4
	OptiFine Build: 20211212-175054
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.2.0 NVIDIA 462.31
	OpenGlRenderer: GeForce GTX 1650 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12
	ModLauncher: 9.0.7+91+master.8569cdf
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 OptiFine TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		client-1.18.1-20211210.034407-srg.jar             |Minecraft                     |minecraft                     |1.18.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		skiing-forge-1.18.1-1.0.0.jar                     |Skiing                        |skiing                        |1.18.1-1.0.0        |DONE      |Manifest: NOSIGNATURE
		forge-1.18.1-39.0.10-universal.jar                |Forge                         |forge                         |39.0.10             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
	Crash Report UUID: 3f324396-8a2f-4bc1-a69b-c1144f84f9b8
	FML: 39.0
	Forge: net.minecraftforge:39.0.10
`

**Comment by Affehund** [comment]
Hi, thank you for reporting this issue. I could reproduce it and already found the error.
